[colors.bright]
black = "0x666666"
blue = "0x81a2be"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0x282a2e"
yellow = "0xf0c674"

[colors.cursor]
cursor = "0xffffff"
text = "0x1d1f21"

[colors.normal]
black = "0x1d1f21"
blue = "0x81a2be"
cyan = "0x70c0ba"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0x373b41"
yellow = "0xe6c547"

[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[schemes.gruvbox_dark.bright]
black = "0x928374"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfabd2f"

[schemes.gruvbox_dark.normal]
black = "0x282828"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0xa89984"
yellow = "0xd79921"

[schemes.gruvbox_dark.primary]
background = "0x1d2021"
foreground = "0xebdbb2"

[schemes.gruvbox_light.bright]
black = "0x928374"
blue = "0x076678"
cyan = "0x427b58"
green = "0x79740e"
magenta = "0x8f3f71"
red = "0x9d0006"
white = "0x3c3836"
yellow = "0xb57614"

[schemes.gruvbox_light.normal]
black = "0xfbf1c7"
blue = "0x458588"
cyan = "0x689d6a"
green = "0x98971a"
magenta = "0xb16286"
red = "0xcc241d"
white = "0x7c6f64"
yellow = "0xd79921"

[schemes.gruvbox_light.primary]
background = "0xf9f5d7"
foreground = "0x3c3836"

[schemes.nord.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[schemes.nord.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[schemes.nord.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[schemes.nord.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[schemes.nord.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[schemes.nord.search.bar]
background = "#434c5e"
foreground = "#d8dee9"

[schemes.nord.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[schemes.nord.selection]
background = "#4c566a"
text = "CellForeground"

[schemes.nord.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[schemes.tomorrow_night.bright]
black = "0x666666"
blue = "0x81a2be"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0x282a2e"
yellow = "0xf0c674"

[schemes.tomorrow_night.cursor]
cursor = "0xffffff"
text = "0x1d1f21"

[schemes.tomorrow_night.normal]
black = "0x1d1f21"
blue = "0x81a2be"
cyan = "0x70c0ba"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0x373b41"
yellow = "0xe6c547"

[schemes.tomorrow_night.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[schemes.tomorrow_night_bright.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0x2a2a2a"
yellow = "0xe7c547"

[schemes.tomorrow_night_bright.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0xb9ca4a"
magenta = "0xc397d8"
red = "0xd54e53"
white = "0x424242"
yellow = "0xe6c547"

[schemes.tomorrow_night_bright.primary]
background = "0x000000"
foreground = "0xeaeaea"
