#!/usr/bin/env bash

set -e

function git_makepkg() {
	repo=$1
	dest=$(echo "$repo" | rev | cut -d "/" -f 1 | rev)

	if [[ -f $dest ]]; then
		echo "--> ${dest} repo already exists, updating..."
		pushd $dest
		git pull --rebase
		popd
	else
		echo "--> ${dest} repo not exists, cloning..."
		git clone $1 $2
	fi

	pushd $dest
	makepkg -si
	popd
}

function install_base_packages() {
	sudo pacman -S --needed --noconfirm \
		alacritty \
		alsa-firmware \
		alsa-ucm-conf \
		aws-cli \
		base-devel \
		chromium \
		dagger \
		direnv \
		dive \
		docker \
		docker-compose \
		fd \
		fzf \
		gdb \
		go \
		gtkmm3 \
		helm \
		helmfile \
		htop \
		hunspell \
		i3-wm \
		i3status \
		jq \
		k9s \
		kitty \
		kubectl \
		kubectx \
		kustomize \
		lazygit \
		make \
		minikube \
		neovim \
		nerd-fonts \
		npm \
		powerline-fonts \
		protobuf \
		pyenv \
		python-pip \
		ripgrep \
		rofi \
		sof-firmware \
		terraform \
		texlab \
		texlive \
		texlive-binextra \
		tmux \
		ttf-droid \
		ttf-firacode-nerd \
		unzip \
		wget \
		yq \
		zathura \
		zip \
		zsh \
		zsh-autosuggestions \
		zsh-completions \
		zsh-syntax-highlighting
}

function install_yay() {
	mkdir -p $HOME/third-party-packages
	pushd $HOME/third-party-packages

	set +e
	yay_path="$(which yay)"
	set -e
	if [[ ! -x "${yay_path}" ]]; then
		git_makepkg https://aur.archlinux.org/yay
	fi

	popd

	ran_yay_gendb="$HOME/.ran_yay_gendb"
	if [[ ! -f "$ran_yay_gendb" ]]; then
		yay -Y --gendb
		touch $ran_yay_gendb
	fi
}

function install_playwright_deps() {
	# Deps for playwright, see: https://github.com/microsoft/playwright/issues/2621#issuecomment-1333085109
	sudo pacman -S --needed --noconfirm \
		libwebp \
		pcre \
		x264

	sudo ln -s /usr/lib/libwebp.so.7 /usr/lib/libwebp.so.6 || true
	sudo ln -s /usr/lib/libpcre.so /usr/lib/libpcre.so.3 || true

	yay -S --needed --noconfirm \
		enchant libffi7 gtk3 nss alsa-lib dbus-glib woff2 libwebp hyphen flite1
}

function install_aur_packages() {
	yay -S --needed --noconfirm \
		jump \
		golangci-lint \
		pyenv-virtualenv \
		kube-ps1 \
		google-cloud-cli \
		google-cloud-cli-gke-gcloud-auth-plugin \
		kind \
		emacs-nativecomp \
		slack-desktop \
		vscodium-bin \
		tilt-bin \
		bazelisk \
		wdisplays \
		github-cli-git \
		oh-my-zsh-git
}



function main() {
	sudo pacman -Sy

	install_base_packages

	install_yay

	install_playwright_deps
	install_aur_packages
}
main
