#!/usr/bin/env bash

set -e

SCRIPT_DIR=$(dirname "$0")

source "$SCRIPT_DIR/install_utils"
source "$SCRIPT_DIR/install_utils_arch"
source "$SCRIPT_DIR/install_utils_ubuntu"
source "$SCRIPT_DIR/install_utils_mac"

function main() {
	pretty_print "Installing everything..." "yellow"

	install_dirs

	# Platform-specific
	if [[ "$OSTYPE" == "linux-gnu"* ]]; then
		if grep -qi "arch" /etc/os-release; then
			pretty_print "Running on Arch Linux" "blue"

			arch_tune_makepkg
			arch_install_base_packages
			arch_install_docker
			arch_install_yay
			arch_install_playwright_deps
			arch_install_aur_packages
		elif grep -qi "ubuntu" /etc/os-release; then
			pretty_print "Running on Ubuntu Linux" "blue"

			ubuntu_install_base_packages
			ubuntu_install_docker
			ubuntu_install_terraform
			ubuntu_install_kubernetes_tools
			ubuntu_install_additional_tools
			ubuntu_install_playwright_deps
		else
			pretty_print "!!! Unsupported Linux distribution. Exiting..." "red"
			cat /etc/os-release
			exit 1
		fi

	elif [[ "$OSTYPE" == "darwin"* ]]; then
		pretty_print "Running on Mac" "blue"

		mac_set_system_settings
		mac_install_packages
	else
		pretty_print "!!! Unsupported operating system. Exiting..." "red"
		exit 1
	fi

	# Generic
	install_git_repos &
	install_tmux_tpm &
	install_go_packages &
	install_node_packages &
	install_doom_emacs &
	install_shell &

	wait

	pretty_print "DONE installing everything." "green"
}

main
