#!/usr/bin/env bash

set -e

function git_makepkg() {
	repo=$1
	dest=$(echo "$repo" | rev | cut -d "/" -f 1 | rev)

	if [[ -f $dest ]]; then
		echo "--> ${dest} repo already exists, updating..."
		pushd $dest
		git pull --rebase
		popd
	else
		echo "--> ${dest} repo not exists, cloning..."
		git clone $1 $2
	fi

	pushd $dest
	makepkg -si
	popd
}

sudo pacman -S --needed --noconfirm \
	tmux \
	wget \
	kitty \
	kubectl \
	kustomize \
	terraform \
	ripgrep \
	fd \
	make \
	helmfile \
	helm \
	go \
	dagger \
	fzf \
	dive \
	docker \
	docker-compose \
	jq \
	yq \
	k9s \
	protobuf \
	zsh \
	zsh-completions \
	zsh-autosuggestions \
	zsh-syntax-highlighting \
	kubectx \
	aws-cli \
	lazygit \
	npm \
	htop \
	pyenv \
	direnv \
	python-pip \
	ttf-firacode-nerd \
	alacritty \
	i3-wm \
	i3status \
	rofi \
	gtkmm3 \
	base-devel \
	powerline-fonts \
	ttf-droid \
	nerd-fonts

mkdir -p $HOME/third-party-packages
pushd $HOME/third-party-packages

set +e
yay_path="$(which yay)"
set -e
if [[ ! -x "${yay_path}" ]]; then
	git_makepkg https://aur.archlinux.org/yay
fi

popd

ran_yay_gendb="$HOME/.ran_yay_gendb"
if [[ ! -f "$ran_yay_gendb" ]]; then
	yay -Y --gendb
	touch $ran_yay_gendb
fi

yay -S --needed --noconfirm \
	jump \
	golangci-lint \
	pyenv-virtualenv \
	kube-ps1 \
	zsh-theme-powerlevel10k \
	google-cloud-cli \
	google-cloud-cli-gke-gcloud-auth-plugin \
	kind \
	emacs-nativecomp \
	slack-desktop \
	vscodium-bin
