#!/usr/bin/env bash

function arch_git_makepkg() {
	repo=$1
	dest=$2

	git_clone "$repo"

	pushd "$dest"
	makepkg -si
	popd
}

function arch_install_base_packages() {
	pretty_print "Installing Arch Base Packages..." "yellow"

	sudo pacman -Sy

	sudo pacman -S --needed --noconfirm \
		alacritty \
		alsa-firmware \
		alsa-ucm-conf \
		aws-cli \
		base-devel \
		chromium \
		dagger \
		direnv \
		dive \
		docker \
		docker-compose \
		fd \
		fzf \
		gdb \
		go \
		gtkmm3 \
		helm \
		helmfile \
		htop \
		hunspell \
		i3-wm \
		i3status \
		jq \
		k9s \
		kitty \
		kubectl \
		kubectx \
		kustomize \
		lazygit \
		make \
		minikube \
		neovim \
		nerd-fonts \
		npm \
		powerline-fonts \
		protobuf \
		pyenv \
		python-pip \
		ripgrep \
		rofi \
		shfmt \
		shellcheck \
		sof-firmware \
		terraform \
		texlab \
		texlive \
		texlive-binextra \
		tmux \
		ttf-droid \
		ttf-firacode-nerd \
		unzip \
		wget \
		yq \
		zathura \
		zip \
		zsh \
		zsh-autosuggestions \
		zsh-completions \
		zsh-syntax-highlighting

	pretty_print "DONE installing Arch Base Packages." "green"
}

function arch_install_yay() {
	pretty_print "Installing 'yay' CLI for AUR download/installs..." "yellow"

	mkdir -p $HOME/third-party-packages
	pushd $HOME/third-party-packages

	set +e
	yay_path="$(which yay)"
	set -e
	if [[ ! -x "${yay_path}" ]]; then
		git_makepkg https://aur.archlinux.org/yay
	fi

	popd

	ran_yay_gendb="$HOME/.ran_yay_gendb"
	if [[ ! -f "$ran_yay_gendb" ]]; then
		yay -Y --gendb
		touch $ran_yay_gendb
	fi

	pretty_print "DONE installing 'yay' CLI for AUR download/installs." "green"
}

function arch_install_playwright_deps() {
	pretty_print "Installing Playwright system library dependencies." "yellow"

	# Deps for playwright, see: https://github.com/microsoft/playwright/issues/2621#issuecomment-1333085109
	sudo pacman -S --needed --noconfirm \
		libwebp \
		pcre \
		x264

	sudo ln -s /usr/lib/libwebp.so.7 /usr/lib/libwebp.so.6 || true
	sudo ln -s /usr/lib/libpcre.so /usr/lib/libpcre.so.3 || true

	yay -S --needed --noconfirm \
		enchant libffi7 gtk3 nss alsa-lib dbus-glib woff2 libwebp hyphen flite1

	pretty_print "DONE installing Playwright system library dependencies." "green"
}

function arch_install_aur_packages() {
	pretty_print "Installing AUR packages..." "yellow"

	yay -S --needed --noconfirm \
		emacs-nativecomp \
		github-cli-git \
		golangci-lint \
		google-cloud-cli \
		google-cloud-cli-gke-gcloud-auth-plugin \
		jump \
		kind \
		kube-ps1 \
		oh-my-zsh-git \
		pyenv-virtualenv \
		slack-desktop \
		tilt-bin \
		vscodium-bin \
		wdisplays

	pretty_print "DONE installing AUR packages." "green"
}
