#!/usr/bin/env bash

set -eoux


# Because of: https://askubuntu.com/questions/1512042/ubuntu-24-04-getting-error-you-must-put-some-deb-src-uris-in-your-sources-list
function ubuntu_set_sources() {
    if ! grep -q '^Types: deb deb-src$' /etc/apt/sources.list.d/ubuntu.sources; then
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
    fi
}

function ubuntu_install_base_packages() {
    pretty_print "Installing Ubuntu Base Packages..." "yellow"

    sudo apt update

    # Install packages via apt
    sudo apt install -y \
        autoconf \
        build-essential \
        curl \
        direnv \
        fonts-powerline \
        gdb \
        git \
        htop \
        hunspell \
        i3-wm \
        i3status \
        imagemagick \
        jq \
        libgtkmm-3.0-dev \
        make \
        nodejs \
        npm \
        protobuf-compiler \
        python3-pip \
        rofi \
        software-properties-common \
        stow \
        texinfo \
        tmux \
        unzip \
        wget \
        xclip \
        xsel \
        zathura \
        zip \
        zsh \
        zsh-syntax-highlighting

    # Install fd as 'fd' instead of 'fdfind'
    if ! command_exists fd; then
        sudo apt install -y fd-find
        sudo ln -s "$(which fdfind)" /usr/local/bin/fd || true
    fi

    pretty_print "DONE installing Ubuntu Base Packages." "green"
}

function ubuntu_install_emacs() {
    if ! command_exists emacs; then
        pretty_print "Installing emacs..." "yellow"


        # Clone the Emacs repository
        git_clone git://git.savannah.gnu.org/emacs.git ${DIR_THIRD_PARTY}/emacs

        pushd ${DIR_THIRD_PARTY}/emacs

        # Enable development libraries and update the apt cache
        sudo sed -i 's/# deb-src/deb-src/' /etc/apt/sources.list && sudo apt update

        # Install necessary dependencies
       sudo apt build-dep -y emacs
       sudo apt install -y libtree-sitter-dev libgccjit-10-dev build-essential libjpeg-dev libpng-dev libtiff-dev libgif-dev libmagickwand-dev \
            libm17n-dev \
            libmagickcore-dev \

        # Generate the configure file
        ./autogen.sh

        # Get the number of CPU cores for compilation
        CORES=$(nproc)

        # Configure Emacs with desired options
        ./configure --with-native-compilation --with-tree-sitter --with-imagemagick --with-json

        # Compile using all available cores
        make -j"$CORES" bootstrap

        # Verify the version
        ./src/emacs --version

        # Install Emacs system-wide
        sudo make install
        
        popd
    else
        pretty_print "DONE installing Emacs." "green"
    fi

}

