---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: ubuntu2004
    box: ubuntu/focal64
    memory: 2048
    cpus: 2
  - name: fedora28
    box: generic/fedora28
    memory: 2048
    cpus: 2

lint: yamllint

provisioner:
  name: ansible
  lint: ansible-lint

scenario:
  name: default
  ephemeral_directory: /tmp/molecule/install/.molecule

verifier:
  name: testinfra
  lint: flake8
