---
- name: Install Common Packages
  package:
    name: "{{ packages_common }}"
    state: present
  become: true

- name: Create tmux plugins directory
  file:
    path: "{{ tmux_plugins_dir }}"
    state: directory
    recurse: true

- name: Download Tmux Plugins
  git:
    repo: "{{ tmux_repo }}"
    dest: "{{ tmux_plugins_dir }}"

- name: Download Dotfiles Repository
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    force: no
  ignore_errors: yes
