[tools]
go = 'latest'
python = 'latest'
pipx = 'latest'
node = 'latest'

pre-commit = 'latest'

terraform = 'latest'
terragrunt = 'latest'
tflint = 'latest'

go-jsonnet = 'latest'
helm = 'latest'
jsonnet-bundler = 'latest'
tanka = 'latest'

usage = 'latest' # Shell autocompletion
watchexec = 'latest' # For 'mise watch'
teleport-community = 'latest' # Teleport CLI

dagger = 'latest'

k3d = 'latest'
k9s = 'latest'
kind = 'latest'
kubectl = 'latest'
kubectx = 'latest'
kubens = 'latest'
kustomize = 'latest'
minikube = 'latest'
tilt = 'latest'
argocd = 'latest'

lazygit = 'latest'

[settings]
experimental = true

[tasks.'install-lsp']
run = [
  'npm install -g vscode-langservers-extracted',
  'npm install -g yaml-language-server',
  'npm install -g bash-language-server',
  'npm install -g dockerfile-language-server-nodejs',
  'npm install -g @taplo/cli',
  'doom sync',
]
