prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues: {}
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs:
    - key: O
      command: |
        tmux new-window -n "PR-{{ .PrNumber }}/{{ .RepoName }}" \
          -c "{{ .RepoPath }}" \
          git fetch --all && cd_worktree {{ .HeadRefName }} && nvim -c ":Octo pr edit {{ .PrNumber }}" || true
repoPaths:
  default_path: ~/code
theme:
  ui:
    table:
      showSeparator: true
pager:
  diff: "nvim"
