---
##########
# Common #
##########
dotfiles_repo: https://github.com/JerusJ/dotfiles.git
dotfiles_dir: "{{ ansible_env['HOME'] }}/dotfiles"

packages_ubuntu:
  - apt-transport-https
  - build-essential
  - libnss3-tools

packages_fedora:
  - "@development-tools"
  - yum-utils

packages_common:
  - bash
  - ca-certificates
  - cargo
  - curl
  - emacs
  - gcc
  - git
  - gnupg2
  - jq
  - make
  - nodejs
  - python3
  - python3-gpg
  - python3-pip
  - sshpass
  - tmux
  - unzip
  - wget
  - zsh
  - direnv

########
# Tmux #
########
tmux_repo: "https://github.com/tmux-plugins/tpm"
tmux_plugins_dir: "{{ ansible_env['HOME'] }}/.tmux/plugins/tpm"


binaries_download_dir: /tmp
binaries_raw:
  - name: kubectl
    version: '1.20.0'
    url: 'https://storage.googleapis.com/kubernetes-release/release/v<VERSION>/bin/linux/amd64/kubectl'

binaries_compressed:
  - name: kustomize
    version: '4.0.5'
    url: 'https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v<VERSION>/kustomize_v<VERSION>_linux_amd64.tar.gz'
