---
##########
# Common #
##########
dotfiles_repo: https://github.com/JerusJ/dotfiles.git
dotfiles_dir: "{{ ansible_env['HOME'] }}/dotfiles"

packages_ubuntu:
  - apt-transport-https
  - build-essential
  - libnss3-tools

packages_fedora:
  - "@development-tools"
  - yum-utils

packages_common:
  - bash
  - ca-certificates
  - cargo
  - curl
  - emacs
  - gcc
  - git
  - gnupg2
  - jq
  - make
  - nodejs
  - python3
  - python3-gpg
  - python3-pip
  - sshpass
  - tmux
  - unzip
  - wget
  - zsh

########
# Tmux #
########
tmux_repo: "https://github.com/tmux-plugins/tpm"
tmux_plugins_dir: "{{ ansible_env['HOME'] }}/.tmux/plugins/tpm"
